export const spotifyDataConstants = {
    SPOTIFY_DATA_TRACK_REQUEST: "SPOTIFY_DATA_TRACK_REQUEST",
    SPOTIFY_DATA_GENRE_REQUEST: "SPOTIFY_DATA_GENRE_REQUEST",
    SPOTIFY_DATA_FAILURE: "SPOTIFY_DATA_FAILURE",
    SPOTIFY_DATA_STORE_TOP_TRACKS_LAST_MONTH: "SPOTIFY_DATA_STORE_TOP_TRACKS_LAST_MONTH",
    SPOTIFY_DATA_STORE_TOP_TRACKS_LAST_6_MONTH: "SPOTIFY_DATA_STORE_TOP_TRACKS_LAST_6_MONTH",
    SPOTIFY_DATA_STORE_TOP_TRACKS_ALL_TIME: "SPOTIFY_DATA_STORE_TOP_TRACKS_ALL_TIME",
    SPOTIFY_DATA_STORE_TOP_GENRES_LAST_MONTH: "SPOTIFY_DATA_STORE_TOP_GENRES_LAST_MONTH",
    SPOTIFY_DATA_STORE_TOP_GENRES_LAST_6_MONTH: "SPOTIFY_DATA_STORE_TOP_GENRES_LAST_6_MONTH",
    SPOTIFY_DATA_STORE_TOP_GENRES_ALL_TIME: "SPOTIFY_DATA_STORE_TOP_GENRES_ALL_TIME"
}