export const userConstants = {
    LOG_USER_REQUEST: "USER_LOG_USER_REQUEST",
    LOG_USER_STORE_USER: "USER_LOG_USER_STORE_USER",
    LOG_USER_FAILURE: "USER_LOG_USER_FAILURE",
    LOG_USER_DISCONNECT: "USER_LOG_USER_DISCONNECT",
    LOG_USER_STORE_TOKENS: "USER_LOG_USER_STORE_TOKENS"
}